name: publish-latest

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: npm install
        run: npm ci

      - name: npm test
        run: npm run test

  publish-npm:
    name: publish-npm
    runs-on: ubuntu-latest
    needs: test
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: npm install
        run: npm ci

      - name: npm build
        run: |
          npm run build
          npm run build:browser

      - name: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN;
          npm publish --tag latest;
