name: publish-latest

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  publish-npm:
    name: publish-npm
    runs-on: ubuntu-18.04
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm ci
      - name: npm build
        run: |
          npm run build
          npm run build:browser
      - name: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN;
          npm publish --tag latest;
